### ISSUE TITLE
Failed to install env

### ISSUE THREAD

**Issue by aetherwu** [madtunebk/ComfyUI-ControlnetAux#6]
mim install mmengine
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "\Programs\Python\Python312\Scripts\mim.exe\__main__.py", line 4, in <module>
  File "\Programs\Python\Python312\Lib\site-packages\mim\__init__.py", line 10, in <module>
    import setuptools  # noqa: F401
    ^^^^^^^^^^^^^^^^^
  File "\Programs\Python\Python312\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
    import setuptools.version
  File "\Programs\Python\Python312\Lib\site-packages\setuptools\version.py", line 1, in <module>
    import pkg_resources
  File "\Programs\Python\Python312\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

**Comment by madtunebk** [comment]
The error you're encountering seems related to incompatibilities between certain Python packages (like setuptools, numpy, and pkg_resources) and Python version 3.12. Specifically, it looks like numpy 2.0 and setuptools might have issues working together on this version of Python.


**Here’s how you can address this issue:**

**1. Downgrade Python to 3.11 or Lower**

- [ ] Since this issue arises in Python 3.12, downgrading to Python 3.11 or an earlier version should resolve the problem. Python 3.11 is stable and widely supported by most packages, so this is a reliable solution.


2. Update Packages

`pip install --upgrade pip setuptools numpy`

- [ ] Sometimes the issue is due to outdated versions of packages that aren't fully compatible with the latest Python versions.

**3. Use a Virtual Environment**

- [ ] Create a virtual environment using Python 3.11 or an earlier version:

`python3.11 -m venv myenv`

- [ ] Activate the environment and install your dependencies. This helps isolate the project and avoid conflicts with system-wide packages.

**4. Check for Known Issues**

- [ ] Sometimes, the issue may be due to a bug that has been reported and is being tracked. You can check the [GitHub repositories](https://github.com/pypa/setuptools) for setuptools, numpy, or pkg_resources to see if others are facing the same issue and if a fix or workaround has been proposed.

**5. Alternative Fixes**

- [ ] If downgrading or updating packages doesn’t solve the problem, consider:

-       Rolling back numpy and setuptools to earlier versions that are known to be compatible with Python 3.12.

-       Explicitly specifying versions of packages in your requirements.txt file to avoid incompatibilities.

**Here is how you can downgrade a package:**
`pip install setuptools==version_number`


Replace version_number with a version that is known to work.

If the issue persists after these steps, I would recommend sticking with Python 3.11 until the packages you need are fully compatible with Python 3.12.

**Comment by aetherwu** [comment]
> The error you're encountering seems related to incompatibilities between certain Python packages (like setuptools, numpy, and pkg_resources) and Python version 3.12. Specifically, it looks like numpy 2.0 and setuptools might have issues working together on this version of Python.
> 
> **Here’s how you can address this issue:**
> 
> **1. Downgrade Python to 3.11 or Lower**
> 
> * [ ]  Since this issue arises in Python 3.12, downgrading to Python 3.11 or an earlier version should resolve the problem. Python 3.11 is stable and widely supported by most packages, so this is a reliable solution.
> 
> 2. Update Packages
> 
> `pip install --upgrade pip setuptools numpy`
> 
> * [ ]  Sometimes the issue is due to outdated versions of packages that aren't fully compatible with the latest Python versions.
> 
> **3. Use a Virtual Environment**
> 
> * [ ]  Create a virtual environment using Python 3.11 or an earlier version:
> 
> `python3.11 -m venv myenv`
> 
> * [ ]  Activate the environment and install your dependencies. This helps isolate the project and avoid conflicts with system-wide packages.
> 
> **4. Check for Known Issues**
> 
> * [ ]  Sometimes, the issue may be due to a bug that has been reported and is being tracked. You can check the [GitHub repositories](https://github.com/pypa/setuptools) for setuptools, numpy, or pkg_resources to see if others are facing the same issue and if a fix or workaround has been proposed.
> 
> **5. Alternative Fixes**
> 
> * [ ]  If downgrading or updating packages doesn’t solve the problem, consider:
> * ```
>     Rolling back numpy and setuptools to earlier versions that are known to be compatible with Python 3.12.
>   ```
> * ```
>     Explicitly specifying versions of packages in your requirements.txt file to avoid incompatibilities.
>   ```
> 
> **Here is how you can downgrade a package:** `pip install setuptools==version_number`
> 
> Replace version_number with a version that is known to work.
> 
> If the issue persists after these steps, I would recommend sticking with Python 3.11 until the packages you need are fully compatible with Python 3.12.

Thank you for your guildence and I will try it again!
